/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ULgovPA32rK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function TopPage() {
  return (
    <>
      <header className="flex items-center justify-between bg-gray-900 px-6 py-4 text-white">
        <div className="flex items-center gap-4">
          <Link className="flex items-center gap-2" href="#">
            <MusicIcon className="h-6 w-6" />
            <span className="text-lg font-semibold">Dig</span>
          </Link>
          <nav className="hidden md:flex items-center gap-4">
            <Link className="hover:text-gray-400" href="#">
              Playlists
            </Link>
            <Link className="hover:text-gray-400" href="#">
              Albums
            </Link>
            <Link className="hover:text-gray-400" href="#">
              Artists
            </Link>
          </nav>
        </div>
        <div className="flex items-center gap-4">
          <div className="relative">
            <SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
            <Input
              className="rounded-md bg-gray-800 pl-10 pr-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-gray-600"
              placeholder="Search"
              type="text"
            />
          </div>
          <Button className="rounded-md px-4 py-2 text-sm" variant="outline">
            Login
          </Button>
        </div>
      </header>
      <main className="bg-gray-900 text-white">
        <div className="container mx-auto py-8">
          <div className="space-y-8">
            <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
              <div className="rounded-lg bg-gray-800 p-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <img



                      alt="Album Cover"
                      className="rounded-md"
                      height={48}
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "48/48",
                        objectFit: "cover",
                      }}
                      width={48}
                    />
                    <div>
                      <h3 className="text-lg font-semibold">Playlist Title</h3>
                      <p className="text-sm text-gray-400">Playlist Creator</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <PlayIcon className="h-5 w-5" />
                    <span className="text-sm">1.2M</span>
                  </div>
                </div>
                <div className="mt-4 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <StarIcon className="h-5 w-5 text-yellow-500" />
                    <span className="text-sm">4.8</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <TrendingUpIcon className="h-5 w-5" />
                    <span className="text-sm">Top 10%</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <GlobeIcon className="h-5 w-5" />
                    <span className="text-sm">Worldwide</span>
                  </div>
                </div>
              </div>
              <div className="rounded-lg bg-gray-800 p-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <img
                      alt="Album Cover"
                      className="rounded-md"
                      height={48}
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "48/48",
                        objectFit: "cover",
                      }}
                      width={48}
                    />
                    <div>
                      <h3 className="text-lg font-semibold">Playlist Title</h3>
                      <p className="text-sm text-gray-400">Playlist Creator</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <PlayIcon className="h-5 w-5" />
                    <span className="text-sm">800K</span>
                  </div>
                </div>
                <div className="mt-4 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <StarIcon className="h-5 w-5 text-yellow-500" />
                    <span className="text-sm">4.5</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <TrendingUpIcon className="h-5 w-5" />
                    <span className="text-sm">Top 20%</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <GlobeIcon className="h-5 w-5" />
                    <span className="text-sm">Worldwide</span>
                  </div>
                </div>
              </div>
              <div className="rounded-lg bg-gray-800 p-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <img
                      alt="Album Cover"
                      className="rounded-md"
                      height={48}
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "48/48",
                        objectFit: "cover",
                      }}
                      width={48}
                    />
                    <div>
                      <h3 className="text-lg font-semibold">Playlist Title</h3>
                      <p className="text-sm text-gray-400">Playlist Creator</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <PlayIcon className="h-5 w-5" />
                    <span className="text-sm">600K</span>
                  </div>
                </div>
                <div className="mt-4 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <StarIcon className="h-5 w-5 text-yellow-500" />
                    <span className="text-sm">4.2</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <TrendingUpIcon className="h-5 w-5" />
                    <span className="text-sm">Top 30%</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <GlobeIcon className="h-5 w-5" />
                    <span className="text-sm">Worldwide</span>
                  </div>
                </div>
              </div>
              <div className="rounded-lg bg-gray-800 p-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <img
                      alt="Album Cover"
                      className="rounded-md"
                      height={48}
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "48/48",
                        objectFit: "cover",
                      }}
                      width={48}
                    />
                    <div>
                      <h3 className="text-lg font-semibold">Playlist Title</h3>
                      <p className="text-sm text-gray-400">Playlist Creator</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <PlayIcon className="h-5 w-5" />
                    <span className="text-sm">400K</span>
                  </div>
                </div>
                <div className="mt-4 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <StarIcon className="h-5 w-5 text-yellow-500" />
                    <span className="text-sm">3.9</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <TrendingUpIcon className="h-5 w-5" />
                    <span className="text-sm">Top 40%</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <GlobeIcon className="h-5 w-5" />
                    <span className="text-sm">Worldwide</span>
                  </div>
                </div>
              </div>
            </div>
            <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
              <div className="rounded-lg bg-gray-800 p-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <img
                      alt="Album Cover"
                      className="rounded-md"
                      height={48}
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "48/48",
                        objectFit: "cover",
                      }}
                      width={48}
                    />
                    <div>
                      <h3 className="text-lg font-semibold">Playlist Title</h3>
                      <p className="text-sm text-gray-400">Playlist Creator</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <PlayIcon className="h-5 w-5" />
                    <span className="text-sm">300K</span>
                  </div>
                </div>
                <div className="mt-4 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <StarIcon className="h-5 w-5 text-yellow-500" />
                    <span className="text-sm">3.7</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <TrendingUpIcon className="h-5 w-5" />
                    <span className="text-sm">Top 50%</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <GlobeIcon className="h-5 w-5" />
                    <span className="text-sm">Worldwide</span>
                  </div>
                </div>
              </div>
              <div className="rounded-lg bg-gray-800 p-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <img
                      alt="Album Cover"
                      className="rounded-md"
                      height={48}
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "48/48",
                        objectFit: "cover",
                      }}
                      width={48}
                    />
                    <div>
                      <h3 className="text-lg font-semibold">Playlist Title</h3>
                      <p className="text-sm text-gray-400">Playlist Creator</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <PlayIcon className="h-5 w-5" />
                    <span className="text-sm">250K</span>
                  </div>
                </div>
                <div className="mt-4 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <StarIcon className="h-5 w-5 text-yellow-500" />
                    <span className="text-sm">3.5</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <TrendingUpIcon className="h-5 w-5" />
                    <span className="text-sm">Top 60%</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <GlobeIcon className="h-5 w-5" />
                    <span className="text-sm">Worldwide</span>
                  </div>
                </div>
              </div>
              <div className="rounded-lg bg-gray-800 p-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <img
                      alt="Album Cover"
                      className="rounded-md"
                      height={48}
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "48/48",
                        objectFit: "cover",
                      }}
                      width={48}
                    />
                    <div>
                      <h3 className="text-lg font-semibold">Playlist Title</h3>
                      <p className="text-sm text-gray-400">Playlist Creator</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <PlayIcon className="h-5 w-5" />
                    <span className="text-sm">180K</span>
                  </div>
                </div>
                <div className="mt-4 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <StarIcon className="h-5 w-5 text-yellow-500" />
                    <span className="text-sm">3.2</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <TrendingUpIcon className="h-5 w-5" />
                    <span className="text-sm">Top 70%</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <GlobeIcon className="h-5 w-5" />
                    <span className="text-sm">Worldwide</span>
                  </div>
                </div>
              </div>
              <div className="rounded-lg bg-gray-800 p-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <img
                      alt="Album Cover"
                      className="rounded-md"
                      height={48}
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "48/48",
                        objectFit: "cover",
                      }}
                      width={48}
                    />
                    <div>
                      <h3 className="text-lg font-semibold">Playlist Title</h3>
                      <p className="text-sm text-gray-400">Playlist Creator</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <PlayIcon className="h-5 w-5" />
                    <span className="text-sm">120K</span>
                  </div>
                </div>
                <div className="mt-4 flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <StarIcon className="h-5 w-5 text-yellow-500" />
                    <span className="text-sm">3.0</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <TrendingUpIcon className="h-5 w-5" />
                    <span className="text-sm">Top 80%</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <GlobeIcon className="h-5 w-5" />
                    <span className="text-sm">Worldwide</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}

import React from 'react';

interface IconProps extends React.SVGAttributes<SVGElement> {}

function GlobeIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20" />
      <path d="M2 12h20" />
    </svg>
  )
}


function MusicIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9 18V5l12-2v13" />
      <circle cx="6" cy="18" r="3" />
      <circle cx="18" cy="16" r="3" />
    </svg>
  )
}


function PlayIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="6 3 20 12 6 21 6 3" />
    </svg>
  )
}


function SearchIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function StarIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


function TrendingUpIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="22 7 13.5 15.5 8.5 10.5 2 17" />
      <polyline points="16 7 22 7 22 13" />
    </svg>
  )
}
